const pages={
 aktuality:{title:'AKTUALITY',intro:'Novinky, události a dění v komunitě Boom Beach.',sections:[['Operace každý den','Přidej se k nám a vyzkoušej sílu svých jednotek na pravidelné Task Force operaci.'],['Co se chystá v srpnu','Sonar Ops, Warships, Crystal Shield, Gunboat Crab, speciální jednotky a další časově omezené události.'],['Komunita','Pro domluvu, dotazy a žádosti o vstup používáme anonymní aplikaci Session.']]},
 rekordy:{title:'REKORDY',intro:'Historie největších úspěchů týmů CZECH a CZECH ELITE.',sections:[['Nový tým CZECH','Založení Task Force #PV9LJUQ2 a návrat na vrchol.'],['Duplexity','Přehled pokoření operace Duplexity našimi týmy.'],['CZECH ELITE','Historické světové a české rekordy Task Force #U0RLR.']]},
 videa:{title:'VIDEA Z TF OPERACÍ',intro:'Záznamy útoků z nejsložitějších základen.',sections:[['Solo útoky','Axiom, Boomtown, Callisto, Complex, Conifold, Cooker a další.'],['Kombinované útoky','Jawline, Redline, Winged, Runway a další operační základny.']]},
 'youtube-videa':{title:'YOUTUBE VIDEA',intro:'Výběr videí, návodů a tvůrců z komunity Boom Beach.',sections:[['Boom Beach youtubeři','Kaktus Boom Beach, SkullCrusher Boom a OP Destroy.'],['Jak na Duplexity','Videa pro Deja Vu, Harmony, Jawline, Motherboard, Runway, Spine, Trinity a Winged.']]},
 jednotky:{title:'JEDNOTKY A ÚTOČNÉ SCHOPNOSTI',intro:'Rychlý rozcestník jednotek a jejich velitelů.',sections:[['Základní jednotky','Rifleman, Heavy, Zooka, Warrior, Tank, Medic, Grenadier, Scorcher, Laser Ranger, Cryoneer, Bombardier, Mech a Rocket Choppa.'],['Velitelé jednotek','Lt. Honu, Sgt. Amani Kapata, Sgt. Antti Pylkäs, Lt. Julius Mass a další.']]},
 budovy:{title:'BUDOVY',intro:'Přehled staveb, obrany a prototypů.',sections:[['Základní stavby','Headquarters, Outpost, Engine Room, Power Core a Mega Core.'],['Ekonomické stavby','Residence, Sawmill, Quarry, Iron Mine, sklady a Vault.'],['Obrana','Sniper Tower, Machine Gun, Mortar, Cannon, Boom Cannon, Rocket Launcher, miny a prototypy.']]},
 tipy:{title:'TIPY A RADY',intro:'Praktické rady pro rychlejší postup a efektivnější útoky.',sections:[['Sochy','Upřednostni červené a fialové sochy pro sílu jednotek a více energie dělového člunu.'],['Suroviny','Jak pracovat s eventy, Resource Reward a minimalizovat rabování zlata.'],['Kalkulátory','Výpočet poškození, kořisti, potřebné GBE a efektivity bombardování.'],['Hraní na PC','Přehled možností pomocí Android emulátorů a upozornění na herní podmínky.']]},
 strategie:{title:'UPGRADE A STRATEGIE',intro:'Aktualizace hry, strategie a návody.',sections:[['Velká aktualizace','Velitelé, gadgety, nové suroviny, denní úkoly, obchody a komunitní události.'],['Vedení útoku','Jak postavit armádu, připravit útok a spolupracovat v Task Force.'],['Rady a návody','České titulky, komunitní videa, známé chyby a změny v obchodech.']]},
 session:{title:'KOMUNIKAČNÍ APLIKACE SESSION',intro:'Anonymní komunikace pro členy aliance a zájemce o vstup.',sections:[['Jak začít','Stáhni Session, vytvoř účet bez telefonu a jako přezdívku použij svůj nick z Boom Beach.'],['Kontakt','Naskenuj týmový QR kód nebo vlož Session ID a napiš nám.']]},
 'pravidla-czech':{title:'PRAVIDLA V NAŠÍ PONORCE',intro:'Jednoduchá pravidla pro přátelskou a fungující Task Force.',sections:[['Chování','Chováme se slušně. Osobní spory řešíme soukromě přes Session.'],['Hodnosti','Leader koordinuje tým. Ostatní hodnosti vycházejí z aktivity, spolupráce a týmového ducha.']]},
 'team-czech':{title:'TASK FORCE CZECH',intro:'#PV9LJUQ2',sections:[['Aktuální týmová tabulka','Žebříček, VP, intely, historie hráčů a operační statistiky jsou na samostatné živé stránce.']]},
 'team-czech-elite':{title:'TASK FORCE CZECH ELITE',intro:'#U0RLR',sections:[['Aktuální týmová tabulka','Aktuální data a statistiky týmu CZECH ELITE jsou na samostatné živé stránce.']]}
};
const nav=[['AKTUALITY','/index.html','aktuality'],['REKORDY','/rekordy/index.html','rekordy'],['VIDEA Z OP','/videa/index.html','videa'],['YOUTUBE VIDEA','/youtube-videa/index.html','youtube-videa'],['JEDNOTKY','/jednotky/index.html','jednotky'],['BUDOVY','/budovy/index.html','budovy'],['TIPY','/tipy/index.html','tipy'],['UPGRADE','/strategie/index.html','strategie']];
const key=document.body.dataset.page||'aktuality',data=pages[key]||pages.aktuality;
const extra=key==='team-czech'?'<div class="actions"><a class="button gold" href="https://pv9ljuq2.boombeach.cz/index.html">OTEVŘÍT TABULKU CZECH</a><a class="button" href="https://link.boombeach.com/?url=boombeach%3A%2F%2FViewTaskforce%3Ftag%3D%23PV9LJUQ2">PŘIPOJIT SE</a></div>':key==='team-czech-elite'?'<div class="actions"><a class="button gold" href="https://u0rlr.boombeach.cz/index.html">OTEVŘÍT TABULKU CZECH ELITE</a><a class="button" href="https://link.boombeach.com/?url=boombeach%3A%2F%2FViewTaskforce%3Ftag%3D%23U0RLR">PŘIPOJIT SE</a></div>':'';
document.querySelector('#app').innerHTML=`<header class="site-shell"><nav class="topbar"><a class="brand supercell" href="https://supercell.com/en/games/boombeach/"><img src="/shared/supercell.png" alt="Supercell"></a><a class="brand youtube" href="https://www.youtube.com/@czechelite/playlists"><img src="/shared/youtube-white.svg" alt="YouTube"></a><a class="brand session" href="/session/index.html"><img src="/shared/session.png" alt="Session"></a><a class="brand team" href="/team-czech/index.html" aria-label="CZECH #PV9LJUQ2"><img src="/shared/team-czech-transparent.png" alt="CZECH #PV9LJUQ2"></a><a class="brand team" href="/team-czech-elite/index.html" aria-label="CZECH ELITE #U0RLR"><img src="/shared/team-elite-transparent.png" alt="CZECH ELITE #U0RLR"></a></nav><nav class="island"><div class="island-menu">${nav.map(([n,h,k])=>`<a href="${h}" ${key===k?'aria-current="page"':''}>${n}</a>`).join('')}</div><div class="construction">UNDER<br>CONSTRUCTION</div></nav></header><main class="page" id="content"><section class="hero"><h1>${data.title}</h1><p>${data.intro}</p>${extra}</section><div class="grid">${data.sections.map(([h,p])=>`<article class="card"><h2>${h}</h2><p>${p}</p></article>`).join('')}</div></main><footer class="footer">BOOMBEACH.CZ · Komunita hráčů Boom Beach</footer>`;
